version: '3.8'

services:
  downfile-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./downloads:/app/downloads
      - ./links:/app/links
      - ./data.json:/app/data.json
    restart: always